# Generated by Django 3.0.6 on 2020-06-20 17:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anwser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Odpowiedź')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('text', models.TextField(verbose_name='Wypowiedź')),
                ('type', models.CharField(choices=[('help', 'Strona pomocy'), ('subpage', 'Podstrona'), ('info', 'Strona informacyjna')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Wypowiedź')),
                ('entry', models.BooleanField(default=False, verbose_name='Czy może zaczynać dialog')),
                ('anwsers', models.ManyToManyField(to='dialog.Anwser', verbose_name='Możliwe odpowiedzi')),
            ],
        ),
        migrations.AddField(
            model_name='anwser',
            name='goto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dialog.Statement', verbose_name='Przejdź do'),
        ),
    ]
