# Generated by Django 3.0.6 on 2020-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0003_populate_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='anwser',
            name='accepted',
            field=models.BooleanField(default=True, verbose_name='Zatwierdzona'),
        ),
    ]
